trigger: 
  branches:
    include:
      - main
      - feature/*

pool: pool_of_agents

variables:
-  name: workingdir
   value: $(System.DefaultWorkingDirectory)/environment/${{parameters.environment}}

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prod

stages: 
  - stage: Build
    jobs:
      - job: terraforminitvalidateplan
        displayName: terraform install init validate plan job
        steps:
        - task: TerraformInstaller@1
          displayName: terraform install
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingdir)'
            backendServiceArm: 'infra-service1'
            backendAzureRmStorageAccountName: 'sgprac'
            backendAzureRmContainerName: 'rajatcontainer'
            backendAzureRmKey: 'dev.tfstate'

        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: $(workingdir)

  - stage: Scaning
    displayName: Scaning Stage
    jobs:
      - job: Sacning
        steps:
        - task: tfsec@1
          displayName: tfsec
          inputs:
            version: 'v1.26.0'
            dir: $(workingdir)
            publishTestResults: true
          continueOnError: true

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'tflint'
            workingDirectory: $(workingdir)

        






  
