trigger: 
  branches:
    include:
      - main
      - feature/*

pool: Agents_pool

variables:
-  name: workingdir
   value: $(System.DefaultWorkingDirectory)/environment/${{parameters.environment}}

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prod

stages: 
  - stage: infraprovision
    jobs:
      - job: terraforminitvalidateplan
        displayName: terraform install init validate plan job
        steps:
        - task: TerraformInstaller@1
          displayName: terraform install
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingdir)'
            backendServiceArm: 'infra-service1'
            backendAzureRmStorageAccountName: 'sgprac'
            backendAzureRmContainerName: 'rajatcontainer'
            backendAzureRmKey: 'backend.tfstate'

        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: $(workingdir)

  - stage: Scaning
    displayName: Scaning Stage
    dependsOn: infraprovision
    jobs:
      - job: Sacning
        steps:
        - task: tfsec@1
          displayName: tfsec
          continueOnError: true
          inputs:
            version: 'v1.26.0'
            dir: $(workingdir)
            publishTestResults: true
          
        - task: PowerShell@2
          displayName: tflint
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: 'tflint'
            workingDirectory: $(workingdir)

  - stage: Infraapply
    displayName: apply stage
    dependsOn: Scaning
    jobs:
      - job: apply
        displayName: apply job
        steps:
        - task: TerraformTask@5
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(workingdir)
            backendServiceArm: 'infra-service1'
            backendAzureRmStorageAccountName: 'sgprac'
            backendAzureRmContainerName: 'rajatcontainer'
            backendAzureRmKey: 'backend.tfstate'
 
        - task: TerraformTask@5
          displayName: plan job
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: $(workingdir)
            environmentServiceNameAzureRM: 'infra-service1'

        - task: TerraformTask@5
          displayName: apply job
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: $(workingdir)
            environmentServiceNameAzureRM: 'infra-service1'




  
