trigger: none
  # branches:
  #   include:
  #     - main
  #     - feature/*

pool: Agents_pool

variables:
-  name: workingdir
   value: $(System.DefaultWorkingDirectory)/environment/dev

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prod

############################################

stages: 
  - stage: Scanning
    displayName: Scanning Stage
    jobs:
      - job: tfsec
        displayName: tfsec job
        steps:
        - template: template/tfsec.yaml

      - job: tflint
        displayName: tflint job
        dependsOn: tfsec
        steps:
        - template: template/tflint.yaml

      - job: checkov
        displayName: checkov job
        dependsOn: tflint
        continueOnError: true
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'checkov -d .'
            workingDirectory: $(workingdir)

##########################################

  # - stage: infraprovision
  #   dependsOn: Scanning
  #   condition: succeeded()
  #   jobs:
  #     - job: terraforminitvalidateplan
  #       displayName: terraform install init validate plan job
  #       steps:
  #       - task: TerraformInstaller@1
  #         displayName: terraform install
  #         inputs:
  #           terraformVersion: 'latest'

  #       - template: template/init.yaml

  #       - task: TerraformTask@5
  #         displayName: terraform validate
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'validate'
  #           workingDirectory: $(workingdir)

  #       - task: TerraformTask@5
  #         displayName: plan job
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'plan'
  #           workingDirectory: '$(workingdir)'
  #           environmentServiceNameAzureRM: 'infra_service1'

############################################

  - stage: infracost
    displayName: infracost stage
    jobs:
      - job: infracost
        displayName: infracost job
        steps:
        - template: template/init.yaml

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'infra_service1'
            workingDirectory: '$(workingdir)'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              infracost auth login
              infracost breakdown --path tfplan --format table
            workingDirectory: '$(workingdir)'

################################################

  # - stage: validation
  #   displayName: validation
  #   jobs:
  #     - job: manualvalidation
  #       displayName: manual validation job
  #       pool: server
  #       steps:
  #       - task: ManualValidation@1
  #         displayName: vaildation
  #         inputs:
  #           notifyUsers: 'rajats12120@gmail.com'
  #           approvers: 'rajats12120@gmail.com'

  # - stage: Infraapply
  #   displayName: apply stage
  #   dependsOn: validation
  #   condition: succeeded()
  #   jobs:
  #     - job: apply
  #       displayName: apply job
  #       steps:
  #       - template: tamplate/init.yaml
 
  #       - task: TerraformTask@5
  #         displayName: apply job
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'apply'
  #           workingDirectory: $(workingdir)
  #           environmentServiceNameAzureRM: 'infra-service1'
